import dotenv from 'dotenv'
dotenv.config()
import nodemailer from 'nodemailer'
let transporter=nodemailer.createTransport({
    service:'gmail',
    auth:{
        user:'cresisconnectora@gmail.com',//your email here
        pass:'xfvrnjxowcebqceo'//your app password here (generated by google)
    }
})
export default  transporter
