import dotenv from 'dotenv'
dotenv.config()
import nodemailer from 'nodemailer'
let transporter=nodemailer.createTransport({
    service:'gmail',
    auth:{
        user://your email here
        pass://your app password here (generated by google)
    }
})
export default  transporter
